<?php

/**
 * BaseDiscipline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property integer $credits
 * @property integer $workload
 * @property string $description
 * 
 * @method string     getCode()        Returns the current record's "code" value
 * @method string     getName()        Returns the current record's "name" value
 * @method integer    getCredits()     Returns the current record's "credits" value
 * @method integer    getWorkload()    Returns the current record's "workload" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method Discipline setCode()        Sets the current record's "code" value
 * @method Discipline setName()        Sets the current record's "name" value
 * @method Discipline setCredits()     Sets the current record's "credits" value
 * @method Discipline setWorkload()    Sets the current record's "workload" value
 * @method Discipline setDescription() Sets the current record's "description" value
 * 
 * @package    academico
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiscipline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('discipline');
        $this->hasColumn('code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 10,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('credits', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('workload', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}