<?php

/**
 * DisciplineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisciplineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisciplineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Discipline');
    }
}