generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Student
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Nome}
      list:
        display: [=name, email]
        title: Alunos
      filter:
        display: [=name, email]
      form:
        display:
          "NONE": [name, email, username, password, password_again]
      edit:
        title: Editar aluno
      new:
        title: Novo aluno
