<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('sf_guard_user', 'email_address', 'string', '255', array(
             'notnull' => '1',
             'unique' => '',
             ));
    }

    public function down()
    {

    }
}