<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('professor', 'professor_user_id_sf_guard_user_id', array(
             'name' => 'professor_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('professor', 'professor_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('professor', 'professor_user_id_sf_guard_user_id');
        $this->removeIndex('professor', 'professor_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}