generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Professor
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          professor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Nome}
      list:
        display: [=name, email]
        title: Professores
      filter:
        display: [=name, email]
      form:
        display:
          "NONE": [name, email, username, password, password_again]
      edit:
        title: Editar Professor
      new:
        title: Novo professor
